import AppKit
import ApplicationServices
// `IsSecureEventInputEnabled()` is a Carbon symbol (HIToolbox), not AppKit.
import Carbon.HIToolbox

/// The two OS conditions that decide whether Kleoth may synthesize a ⌘V
/// (design §3.20 / §5.5). Both are cheap, both are re-read at paste time —
/// the controller already checked them at chord-down, but focus can move to a
/// password field (or the user can revoke Accessibility) while we transcribe.
enum InsertionEnvironment {
    /// `CGEvent.post` to another app's session requires Accessibility trust.
    static var isAccessibilityTrusted: Bool {
        AXIsProcessTrusted()
    }

    /// Secure event input (a password field, the login window, some terminals)
    /// swallows synthetic keystrokes silently — refuse rather than no-op.
    static var isSecureInputActive: Bool {
        IsSecureEventInputEnabled()
    }
}

/// nspasteboard.org markers. Clipboard managers (Maccy, Paste, Raycast…) skip
/// items carrying `TransientType`/`AutoGeneratedType`, which is exactly what we
/// want for the text we are about to paste and then remove again — it should
/// not pollute the user's clipboard history.
///
/// ⚠️ Refusal paths (`TextInsertionError`) write the text WITHOUT the transient
/// markers: there we are not going to restore anything and the user has to
/// press ⌘V by hand, so the text must stay recoverable/visible to their
/// clipboard manager.
extension NSPasteboard.PasteboardType {
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let nsPasteboardSource = NSPasteboard.PasteboardType("org.nspasteboard.source")
}
